# Generated by Django 3.1.6 on 2021-02-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=255)),
                ('memeUrl', models.URLField()),
            ],
        ),
    ]
