# Generated by Django 3.1.6 on 2021-02-06 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmemeAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memedata',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='memedata',
            old_name='memeUrl',
            new_name='url',
        ),
    ]
